
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.9.9
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install prerequisites'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'debug.py'

