
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'

- task: PythonScript@0
  displayName: 'Create markdown'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install prerequisites'

- script: |
    python main.py --source example/src/meetingcapturedemo --output example/
  condition: succeededOrFailed()
  displayName: 'Create markdown down'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunTitle: 'Python $(PYTHON_VERSION)'